# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf7e61ef89216fff98366e87c9167bcc5414ffb4fe7a6f944e7f0c40428cd01c197b86659d5bec2f18c744daaa8542a6877d3737b9d67ec2c395c3135e6f1a1
  twilio_sid: AC09b42221ca3d5313b059385b096539a0
  twilio_token: 41b6a85d2ded8a6ecbbc7480a82807d0
  twilio_number: '+13392158135'
#  twilio_number: '+15005550006'
#  twilio_sid: AC15c1c57b653605f016778af536d9ea92
#  twilio_token: e472074010f28f60d5895e22a052ba88
#  twilio_number: '+13392158135'

test:
  secret_key_base: 3b7ed89917f5025916676b567c12ac599a361225b0e49c08676a975b476b89012a3828c3332230fd1aea79976391b5ae2fc515a5e927e5b4fb1611caa253f857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV['SECRET_KEY_BASE']
  secret_token: ENV['SECRET_TOKEN']

  twilio_sid: AC15c1c57b653605f016778af536d9ea92
  twilio_token: e472074010f28f60d5895e22a052ba88
  twilio_number: '+13392158135'
